### ISSUE TITLE
현행 이슈 챗봇의 전체적인 과정에 대해 설명해 드릴까요?

### ISSUE THREAD

**Issue by 2404589803** [deep-diver/hf-daily-paper-newsletter#4]
이슈 챗봇의 전체적인 과정에 대해 설명해 주실 수 있을까요? 그리고 그가 논문을 다운로드 가능한 데이터로 어떻게 변환하는지도 설명해 주실 수 있을까요?

**Comment by deep-diver** [comment]
이슈 챗봇이 뭔가요?

**Comment by 2404589803** [comment]
표현에 실수가 있네요 🤗 데일리페이퍼 뉴스레터 봇은 어떻게 작동하나요?

**Comment by deep-diver** [comment]
다음 페이스북 포스팅을 확인해 주세요! 그리고 전체 구조도는 아래 그림과 같습니다.

<img width="1394" alt="스크린샷 2024-01-18 오후 1 08 05" src="https://github.com/deep-diver/hf-daily-paper-newsletter/assets/26025527/88f5330a-2d82-4728-9b19-2a88e546072f">

https://www.facebook.com/groups/codingeverybody/?multi_permalinks=24965608649719669

**Comment by 2404589803** [comment]
답변해 주셔서 감사합니다！
